nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled
    - ./etc/nginx/conf:/etc/nginx/conf
  links:
    - php
  log_driver: "json-file"
  log_opt:
    max-size: "16k"
    max-file: "2"

php:
  image: php:7.0-fpm
  volumes:
    - ./www:/var/www/html
    - ./etc/php:/usr/local/etc/php
  log_driver: "json-file"
  log_opt:
    max-size: "16k"
    max-file: "2"
